/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExpXouItem extends PItem
{
    private PItem _item_;
    private TXou _xou_;
    private PLogTermo _logTermo_;

    public AExpXouItem()
    {
        // Constructor
    }

    public AExpXouItem(
        @SuppressWarnings("hiding") PItem _item_,
        @SuppressWarnings("hiding") TXou _xou_,
        @SuppressWarnings("hiding") PLogTermo _logTermo_)
    {
        // Constructor
        setItem(_item_);

        setXou(_xou_);

        setLogTermo(_logTermo_);

    }

    @Override
    public Object clone()
    {
        return new AExpXouItem(
            cloneNode(this._item_),
            cloneNode(this._xou_),
            cloneNode(this._logTermo_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpXouItem(this);
    }

    public PItem getItem()
    {
        return this._item_;
    }

    public void setItem(PItem node)
    {
        if(this._item_ != null)
        {
            this._item_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._item_ = node;
    }

    public TXou getXou()
    {
        return this._xou_;
    }

    public void setXou(TXou node)
    {
        if(this._xou_ != null)
        {
            this._xou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._xou_ = node;
    }

    public PLogTermo getLogTermo()
    {
        return this._logTermo_;
    }

    public void setLogTermo(PLogTermo node)
    {
        if(this._logTermo_ != null)
        {
            this._logTermo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logTermo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._item_)
            + toString(this._xou_)
            + toString(this._logTermo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._item_ == child)
        {
            this._item_ = null;
            return;
        }

        if(this._xou_ == child)
        {
            this._xou_ = null;
            return;
        }

        if(this._logTermo_ == child)
        {
            this._logTermo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._item_ == oldChild)
        {
            setItem((PItem) newChild);
            return;
        }

        if(this._xou_ == oldChild)
        {
            setXou((TXou) newChild);
            return;
        }

        if(this._logTermo_ == oldChild)
        {
            setLogTermo((PLogTermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
