/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AExpAritmeticaExp extends PExp
{
    private PExpArit _expArit_;

    public AExpAritmeticaExp()
    {
        // Constructor
    }

    public AExpAritmeticaExp(
        @SuppressWarnings("hiding") PExpArit _expArit_)
    {
        // Constructor
        setExpArit(_expArit_);

    }

    @Override
    public Object clone()
    {
        return new AExpAritmeticaExp(
            cloneNode(this._expArit_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpAritmeticaExp(this);
    }

    public PExpArit getExpArit()
    {
        return this._expArit_;
    }

    public void setExpArit(PExpArit node)
    {
        if(this._expArit_ != null)
        {
            this._expArit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expArit_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expArit_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expArit_ == child)
        {
            this._expArit_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expArit_ == oldChild)
        {
            setExpArit((PExpArit) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
