/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AIgualOperadores extends POperadores
{
    private TIgualLog _igualLog_;

    public AIgualOperadores()
    {
        // Constructor
    }

    public AIgualOperadores(
        @SuppressWarnings("hiding") TIgualLog _igualLog_)
    {
        // Constructor
        setIgualLog(_igualLog_);

    }

    @Override
    public Object clone()
    {
        return new AIgualOperadores(
            cloneNode(this._igualLog_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIgualOperadores(this);
    }

    public TIgualLog getIgualLog()
    {
        return this._igualLog_;
    }

    public void setIgualLog(TIgualLog node)
    {
        if(this._igualLog_ != null)
        {
            this._igualLog_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._igualLog_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._igualLog_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._igualLog_ == child)
        {
            this._igualLog_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._igualLog_ == oldChild)
        {
            setIgualLog((TIgualLog) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
