/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ALogicaExpLogica extends PExpLogica
{
    private PLogica _logica_;

    public ALogicaExpLogica()
    {
        // Constructor
    }

    public ALogicaExpLogica(
        @SuppressWarnings("hiding") PLogica _logica_)
    {
        // Constructor
        setLogica(_logica_);

    }

    @Override
    public Object clone()
    {
        return new ALogicaExpLogica(
            cloneNode(this._logica_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogicaExpLogica(this);
    }

    public PLogica getLogica()
    {
        return this._logica_;
    }

    public void setLogica(PLogica node)
    {
        if(this._logica_ != null)
        {
            this._logica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logica_ == child)
        {
            this._logica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logica_ == oldChild)
        {
            setLogica((PLogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
