/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMaisExpArit extends PExpArit
{
    private PExpArit _expArit_;
    private TMais _mais_;
    private PTermo _termo_;

    public AMaisExpArit()
    {
        // Constructor
    }

    public AMaisExpArit(
        @SuppressWarnings("hiding") PExpArit _expArit_,
        @SuppressWarnings("hiding") TMais _mais_,
        @SuppressWarnings("hiding") PTermo _termo_)
    {
        // Constructor
        setExpArit(_expArit_);

        setMais(_mais_);

        setTermo(_termo_);

    }

    @Override
    public Object clone()
    {
        return new AMaisExpArit(
            cloneNode(this._expArit_),
            cloneNode(this._mais_),
            cloneNode(this._termo_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaisExpArit(this);
    }

    public PExpArit getExpArit()
    {
        return this._expArit_;
    }

    public void setExpArit(PExpArit node)
    {
        if(this._expArit_ != null)
        {
            this._expArit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expArit_ = node;
    }

    public TMais getMais()
    {
        return this._mais_;
    }

    public void setMais(TMais node)
    {
        if(this._mais_ != null)
        {
            this._mais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mais_ = node;
    }

    public PTermo getTermo()
    {
        return this._termo_;
    }

    public void setTermo(PTermo node)
    {
        if(this._termo_ != null)
        {
            this._termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expArit_)
            + toString(this._mais_)
            + toString(this._termo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expArit_ == child)
        {
            this._expArit_ = null;
            return;
        }

        if(this._mais_ == child)
        {
            this._mais_ = null;
            return;
        }

        if(this._termo_ == child)
        {
            this._termo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expArit_ == oldChild)
        {
            setExpArit((PExpArit) newChild);
            return;
        }

        if(this._mais_ == oldChild)
        {
            setMais((TMais) newChild);
            return;
        }

        if(this._termo_ == oldChild)
        {
            setTermo((PTermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
