/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMultiplicacaoTermo extends PTermo
{
    private PTermo _termo_;
    private TMult _mult_;
    private PUnario _unario_;

    public AMultiplicacaoTermo()
    {
        // Constructor
    }

    public AMultiplicacaoTermo(
        @SuppressWarnings("hiding") PTermo _termo_,
        @SuppressWarnings("hiding") TMult _mult_,
        @SuppressWarnings("hiding") PUnario _unario_)
    {
        // Constructor
        setTermo(_termo_);

        setMult(_mult_);

        setUnario(_unario_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplicacaoTermo(
            cloneNode(this._termo_),
            cloneNode(this._mult_),
            cloneNode(this._unario_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplicacaoTermo(this);
    }

    public PTermo getTermo()
    {
        return this._termo_;
    }

    public void setTermo(PTermo node)
    {
        if(this._termo_ != null)
        {
            this._termo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo_ = node;
    }

    public TMult getMult()
    {
        return this._mult_;
    }

    public void setMult(TMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    public PUnario getUnario()
    {
        return this._unario_;
    }

    public void setUnario(PUnario node)
    {
        if(this._unario_ != null)
        {
            this._unario_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unario_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termo_)
            + toString(this._mult_)
            + toString(this._unario_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termo_ == child)
        {
            this._termo_ = null;
            return;
        }

        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        if(this._unario_ == child)
        {
            this._unario_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termo_ == oldChild)
        {
            setTermo((PTermo) newChild);
            return;
        }

        if(this._mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(this._unario_ == oldChild)
        {
            setUnario((PUnario) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
