/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AMultiploId extends PMultiploId
{
    private final LinkedList<PMultiIdentificador> _multiIdentificador_ = new LinkedList<PMultiIdentificador>();

    public AMultiploId()
    {
        // Constructor
    }

    public AMultiploId(
        @SuppressWarnings("hiding") List<PMultiIdentificador> _multiIdentificador_)
    {
        // Constructor
        setMultiIdentificador(_multiIdentificador_);

    }

    @Override
    public Object clone()
    {
        return new AMultiploId(
            cloneList(this._multiIdentificador_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiploId(this);
    }

    public LinkedList<PMultiIdentificador> getMultiIdentificador()
    {
        return this._multiIdentificador_;
    }

    public void setMultiIdentificador(List<PMultiIdentificador> list)
    {
        this._multiIdentificador_.clear();
        this._multiIdentificador_.addAll(list);
        for(PMultiIdentificador e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multiIdentificador_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multiIdentificador_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PMultiIdentificador> i = this._multiIdentificador_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMultiIdentificador) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
