/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMultiploDeclaracao extends PDeclaracao
{
    private PDeclaracao _declaracao_;
    private PVariavelDefinicao _variavelDefinicao_;

    public AMultiploDeclaracao()
    {
        // Constructor
    }

    public AMultiploDeclaracao(
        @SuppressWarnings("hiding") PDeclaracao _declaracao_,
        @SuppressWarnings("hiding") PVariavelDefinicao _variavelDefinicao_)
    {
        // Constructor
        setDeclaracao(_declaracao_);

        setVariavelDefinicao(_variavelDefinicao_);

    }

    @Override
    public Object clone()
    {
        return new AMultiploDeclaracao(
            cloneNode(this._declaracao_),
            cloneNode(this._variavelDefinicao_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiploDeclaracao(this);
    }

    public PDeclaracao getDeclaracao()
    {
        return this._declaracao_;
    }

    public void setDeclaracao(PDeclaracao node)
    {
        if(this._declaracao_ != null)
        {
            this._declaracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracao_ = node;
    }

    public PVariavelDefinicao getVariavelDefinicao()
    {
        return this._variavelDefinicao_;
    }

    public void setVariavelDefinicao(PVariavelDefinicao node)
    {
        if(this._variavelDefinicao_ != null)
        {
            this._variavelDefinicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavelDefinicao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracao_)
            + toString(this._variavelDefinicao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracao_ == child)
        {
            this._declaracao_ = null;
            return;
        }

        if(this._variavelDefinicao_ == child)
        {
            this._variavelDefinicao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declaracao_ == oldChild)
        {
            setDeclaracao((PDeclaracao) newChild);
            return;
        }

        if(this._variavelDefinicao_ == oldChild)
        {
            setVariavelDefinicao((PVariavelDefinicao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
