/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AMultiploComando extends PComando
{
    private PComando _comando_;
    private PDefinicaoComando _definicaoComando_;

    public AMultiploComando()
    {
        // Constructor
    }

    public AMultiploComando(
        @SuppressWarnings("hiding") PComando _comando_,
        @SuppressWarnings("hiding") PDefinicaoComando _definicaoComando_)
    {
        // Constructor
        setComando(_comando_);

        setDefinicaoComando(_definicaoComando_);

    }

    @Override
    public Object clone()
    {
        return new AMultiploComando(
            cloneNode(this._comando_),
            cloneNode(this._definicaoComando_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiploComando(this);
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    public PDefinicaoComando getDefinicaoComando()
    {
        return this._definicaoComando_;
    }

    public void setDefinicaoComando(PDefinicaoComando node)
    {
        if(this._definicaoComando_ != null)
        {
            this._definicaoComando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._definicaoComando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comando_)
            + toString(this._definicaoComando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        if(this._definicaoComando_ == child)
        {
            this._definicaoComando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        if(this._definicaoComando_ == oldChild)
        {
            setDefinicaoComando((PDefinicaoComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
