/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ANaoExpLogica extends PExpLogica
{
    private TNao _nao_;
    private PLogica _logica_;

    public ANaoExpLogica()
    {
        // Constructor
    }

    public ANaoExpLogica(
        @SuppressWarnings("hiding") TNao _nao_,
        @SuppressWarnings("hiding") PLogica _logica_)
    {
        // Constructor
        setNao(_nao_);

        setLogica(_logica_);

    }

    @Override
    public Object clone()
    {
        return new ANaoExpLogica(
            cloneNode(this._nao_),
            cloneNode(this._logica_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANaoExpLogica(this);
    }

    public TNao getNao()
    {
        return this._nao_;
    }

    public void setNao(TNao node)
    {
        if(this._nao_ != null)
        {
            this._nao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nao_ = node;
    }

    public PLogica getLogica()
    {
        return this._logica_;
    }

    public void setLogica(PLogica node)
    {
        if(this._logica_ != null)
        {
            this._logica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nao_)
            + toString(this._logica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nao_ == child)
        {
            this._nao_ = null;
            return;
        }

        if(this._logica_ == child)
        {
            this._logica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nao_ == oldChild)
        {
            setNao((TNao) newChild);
            return;
        }

        if(this._logica_ == oldChild)
        {
            setLogica((PLogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
