/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AOpcionalSenaoCaso extends POpcionalSenaoCaso
{
    private PSenaoCaso _senaoCaso_;

    public AOpcionalSenaoCaso()
    {
        // Constructor
    }

    public AOpcionalSenaoCaso(
        @SuppressWarnings("hiding") PSenaoCaso _senaoCaso_)
    {
        // Constructor
        setSenaoCaso(_senaoCaso_);

    }

    @Override
    public Object clone()
    {
        return new AOpcionalSenaoCaso(
            cloneNode(this._senaoCaso_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpcionalSenaoCaso(this);
    }

    public PSenaoCaso getSenaoCaso()
    {
        return this._senaoCaso_;
    }

    public void setSenaoCaso(PSenaoCaso node)
    {
        if(this._senaoCaso_ != null)
        {
            this._senaoCaso_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senaoCaso_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._senaoCaso_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._senaoCaso_ == child)
        {
            this._senaoCaso_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._senaoCaso_ == oldChild)
        {
            setSenaoCaso((PSenaoCaso) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
