/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AOpcionalSenaoSe extends POpcionalSenaoSe
{
    private PSenaoSe _senaoSe_;

    public AOpcionalSenaoSe()
    {
        // Constructor
    }

    public AOpcionalSenaoSe(
        @SuppressWarnings("hiding") PSenaoSe _senaoSe_)
    {
        // Constructor
        setSenaoSe(_senaoSe_);

    }

    @Override
    public Object clone()
    {
        return new AOpcionalSenaoSe(
            cloneNode(this._senaoSe_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpcionalSenaoSe(this);
    }

    public PSenaoSe getSenaoSe()
    {
        return this._senaoSe_;
    }

    public void setSenaoSe(PSenaoSe node)
    {
        if(this._senaoSe_ != null)
        {
            this._senaoSe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senaoSe_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._senaoSe_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._senaoSe_ == child)
        {
            this._senaoSe_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._senaoSe_ == oldChild)
        {
            setSenaoSe((PSenaoSe) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
