/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AOuLogica extends PLogica
{
    private PLogica _logica_;
    private TOu _ou_;
    private PRelacional _relacional_;

    public AOuLogica()
    {
        // Constructor
    }

    public AOuLogica(
        @SuppressWarnings("hiding") PLogica _logica_,
        @SuppressWarnings("hiding") TOu _ou_,
        @SuppressWarnings("hiding") PRelacional _relacional_)
    {
        // Constructor
        setLogica(_logica_);

        setOu(_ou_);

        setRelacional(_relacional_);

    }

    @Override
    public Object clone()
    {
        return new AOuLogica(
            cloneNode(this._logica_),
            cloneNode(this._ou_),
            cloneNode(this._relacional_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOuLogica(this);
    }

    public PLogica getLogica()
    {
        return this._logica_;
    }

    public void setLogica(PLogica node)
    {
        if(this._logica_ != null)
        {
            this._logica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logica_ = node;
    }

    public TOu getOu()
    {
        return this._ou_;
    }

    public void setOu(TOu node)
    {
        if(this._ou_ != null)
        {
            this._ou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ou_ = node;
    }

    public PRelacional getRelacional()
    {
        return this._relacional_;
    }

    public void setRelacional(PRelacional node)
    {
        if(this._relacional_ != null)
        {
            this._relacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relacional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logica_)
            + toString(this._ou_)
            + toString(this._relacional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logica_ == child)
        {
            this._logica_ = null;
            return;
        }

        if(this._ou_ == child)
        {
            this._ou_ = null;
            return;
        }

        if(this._relacional_ == child)
        {
            this._relacional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logica_ == oldChild)
        {
            setLogica((PLogica) newChild);
            return;
        }

        if(this._ou_ == oldChild)
        {
            setOu((TOu) newChild);
            return;
        }

        if(this._relacional_ == oldChild)
        {
            setRelacional((PRelacional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
