/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASenaoSenaoSe extends PSenaoSe
{
    private TSenao _senao_;

    public ASenaoSenaoSe()
    {
        // Constructor
    }

    public ASenaoSenaoSe(
        @SuppressWarnings("hiding") TSenao _senao_)
    {
        // Constructor
        setSenao(_senao_);

    }

    @Override
    public Object clone()
    {
        return new ASenaoSenaoSe(
            cloneNode(this._senao_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASenaoSenaoSe(this);
    }

    public TSenao getSenao()
    {
        return this._senao_;
    }

    public void setSenao(TSenao node)
    {
        if(this._senao_ != null)
        {
            this._senao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._senao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._senao_ == child)
        {
            this._senao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._senao_ == oldChild)
        {
            setSenao((TSenao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
