/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AUnicoComando extends PComando
{
    private PDefinicaoComando _definicaoComando_;

    public AUnicoComando()
    {
        // Constructor
    }

    public AUnicoComando(
        @SuppressWarnings("hiding") PDefinicaoComando _definicaoComando_)
    {
        // Constructor
        setDefinicaoComando(_definicaoComando_);

    }

    @Override
    public Object clone()
    {
        return new AUnicoComando(
            cloneNode(this._definicaoComando_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnicoComando(this);
    }

    public PDefinicaoComando getDefinicaoComando()
    {
        return this._definicaoComando_;
    }

    public void setDefinicaoComando(PDefinicaoComando node)
    {
        if(this._definicaoComando_ != null)
        {
            this._definicaoComando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._definicaoComando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._definicaoComando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._definicaoComando_ == child)
        {
            this._definicaoComando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._definicaoComando_ == oldChild)
        {
            setDefinicaoComando((PDefinicaoComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
