/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AUnicoDeclaracao extends PDeclaracao
{
    private PVariavelDefinicao _variavelDefinicao_;

    public AUnicoDeclaracao()
    {
        // Constructor
    }

    public AUnicoDeclaracao(
        @SuppressWarnings("hiding") PVariavelDefinicao _variavelDefinicao_)
    {
        // Constructor
        setVariavelDefinicao(_variavelDefinicao_);

    }

    @Override
    public Object clone()
    {
        return new AUnicoDeclaracao(
            cloneNode(this._variavelDefinicao_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnicoDeclaracao(this);
    }

    public PVariavelDefinicao getVariavelDefinicao()
    {
        return this._variavelDefinicao_;
    }

    public void setVariavelDefinicao(PVariavelDefinicao node)
    {
        if(this._variavelDefinicao_ != null)
        {
            this._variavelDefinicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavelDefinicao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variavelDefinicao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variavelDefinicao_ == child)
        {
            this._variavelDefinicao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variavelDefinicao_ == oldChild)
        {
            setVariavelDefinicao((PVariavelDefinicao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
