/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AXouLogica extends PLogica
{
    private PLogica _logica_;
    private TXou _xou_;
    private PRelacional _relacional_;

    public AXouLogica()
    {
        // Constructor
    }

    public AXouLogica(
        @SuppressWarnings("hiding") PLogica _logica_,
        @SuppressWarnings("hiding") TXou _xou_,
        @SuppressWarnings("hiding") PRelacional _relacional_)
    {
        // Constructor
        setLogica(_logica_);

        setXou(_xou_);

        setRelacional(_relacional_);

    }

    @Override
    public Object clone()
    {
        return new AXouLogica(
            cloneNode(this._logica_),
            cloneNode(this._xou_),
            cloneNode(this._relacional_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAXouLogica(this);
    }

    public PLogica getLogica()
    {
        return this._logica_;
    }

    public void setLogica(PLogica node)
    {
        if(this._logica_ != null)
        {
            this._logica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logica_ = node;
    }

    public TXou getXou()
    {
        return this._xou_;
    }

    public void setXou(TXou node)
    {
        if(this._xou_ != null)
        {
            this._xou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._xou_ = node;
    }

    public PRelacional getRelacional()
    {
        return this._relacional_;
    }

    public void setRelacional(PRelacional node)
    {
        if(this._relacional_ != null)
        {
            this._relacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relacional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logica_)
            + toString(this._xou_)
            + toString(this._relacional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logica_ == child)
        {
            this._logica_ = null;
            return;
        }

        if(this._xou_ == child)
        {
            this._xou_ = null;
            return;
        }

        if(this._relacional_ == child)
        {
            this._relacional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logica_ == oldChild)
        {
            setLogica((PLogica) newChild);
            return;
        }

        if(this._xou_ == oldChild)
        {
            setXou((TXou) newChild);
            return;
        }

        if(this._relacional_ == oldChild)
        {
            setRelacional((PRelacional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
