/* This file was generated by SableCC (http://www.sablecc.org/). */

package analysis;

import java.util.*;
import node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPProgram().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAProgram(AProgram node)
    {
        defaultIn(node);
    }

    public void outAProgram(AProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProgram(AProgram node)
    {
        inAProgram(node);
        if(node.getPrograma() != null)
        {
            node.getPrograma().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getInicio() != null)
        {
            node.getInicio().apply(this);
        }
        if(node.getDeclaracao() != null)
        {
            node.getDeclaracao().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getFim() != null)
        {
            node.getFim().apply(this);
        }
        outAProgram(node);
    }

    public void inAUnicoDeclaracao(AUnicoDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAUnicoDeclaracao(AUnicoDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoDeclaracao(AUnicoDeclaracao node)
    {
        inAUnicoDeclaracao(node);
        if(node.getVariavelDefinicao() != null)
        {
            node.getVariavelDefinicao().apply(this);
        }
        outAUnicoDeclaracao(node);
    }

    public void inAMultiploDeclaracao(AMultiploDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAMultiploDeclaracao(AMultiploDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploDeclaracao(AMultiploDeclaracao node)
    {
        inAMultiploDeclaracao(node);
        if(node.getDeclaracao() != null)
        {
            node.getDeclaracao().apply(this);
        }
        if(node.getVariavelDefinicao() != null)
        {
            node.getVariavelDefinicao().apply(this);
        }
        outAMultiploDeclaracao(node);
    }

    public void inAConstDeclaracao(AConstDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAConstDeclaracao(AConstDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConstDeclaracao(AConstDeclaracao node)
    {
        inAConstDeclaracao(node);
        if(node.getConstante() != null)
        {
            node.getConstante().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAConstDeclaracao(node);
    }

    public void inAVariavelDefinicao(AVariavelDefinicao node)
    {
        defaultIn(node);
    }

    public void outAVariavelDefinicao(AVariavelDefinicao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariavelDefinicao(AVariavelDefinicao node)
    {
        inAVariavelDefinicao(node);
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getMultiploId() != null)
        {
            node.getMultiploId().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAVariavelDefinicao(node);
    }

    public void inAUnicoIdentificador(AUnicoIdentificador node)
    {
        defaultIn(node);
    }

    public void outAUnicoIdentificador(AUnicoIdentificador node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoIdentificador(AUnicoIdentificador node)
    {
        inAUnicoIdentificador(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAUnicoIdentificador(node);
    }

    public void inAMultiploIdentificador(AMultiploIdentificador node)
    {
        defaultIn(node);
    }

    public void outAMultiploIdentificador(AMultiploIdentificador node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploIdentificador(AMultiploIdentificador node)
    {
        inAMultiploIdentificador(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getLColc() != null)
        {
            node.getLColc().apply(this);
        }
        if(node.getNumInteiro() != null)
        {
            node.getNumInteiro().apply(this);
        }
        if(node.getRColc() != null)
        {
            node.getRColc().apply(this);
        }
        outAMultiploIdentificador(node);
    }

    public void inAStringValor(AStringValor node)
    {
        defaultIn(node);
    }

    public void outAStringValor(AStringValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringValor(AStringValor node)
    {
        inAStringValor(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAStringValor(node);
    }

    public void inAInteiroValor(AInteiroValor node)
    {
        defaultIn(node);
    }

    public void outAInteiroValor(AInteiroValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInteiroValor(AInteiroValor node)
    {
        inAInteiroValor(node);
        if(node.getNumInteiro() != null)
        {
            node.getNumInteiro().apply(this);
        }
        outAInteiroValor(node);
    }

    public void inARealValor(ARealValor node)
    {
        defaultIn(node);
    }

    public void outARealValor(ARealValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealValor(ARealValor node)
    {
        inARealValor(node);
        if(node.getNumReal() != null)
        {
            node.getNumReal().apply(this);
        }
        outARealValor(node);
    }

    public void inATipoRealTipo(ATipoRealTipo node)
    {
        defaultIn(node);
    }

    public void outATipoRealTipo(ATipoRealTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoRealTipo(ATipoRealTipo node)
    {
        inATipoRealTipo(node);
        if(node.getReal() != null)
        {
            node.getReal().apply(this);
        }
        outATipoRealTipo(node);
    }

    public void inATipoIntTipo(ATipoIntTipo node)
    {
        defaultIn(node);
    }

    public void outATipoIntTipo(ATipoIntTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoIntTipo(ATipoIntTipo node)
    {
        inATipoIntTipo(node);
        if(node.getInteiro() != null)
        {
            node.getInteiro().apply(this);
        }
        outATipoIntTipo(node);
    }

    public void inATipoCaractereTipo(ATipoCaractereTipo node)
    {
        defaultIn(node);
    }

    public void outATipoCaractereTipo(ATipoCaractereTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoCaractereTipo(ATipoCaractereTipo node)
    {
        inATipoCaractereTipo(node);
        if(node.getCaractere() != null)
        {
            node.getCaractere().apply(this);
        }
        outATipoCaractereTipo(node);
    }

    public void inAMultiIdentificador(AMultiIdentificador node)
    {
        defaultIn(node);
    }

    public void outAMultiIdentificador(AMultiIdentificador node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiIdentificador(AMultiIdentificador node)
    {
        inAMultiIdentificador(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        outAMultiIdentificador(node);
    }

    public void inAMultiploId(AMultiploId node)
    {
        defaultIn(node);
    }

    public void outAMultiploId(AMultiploId node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploId(AMultiploId node)
    {
        inAMultiploId(node);
        {
            List<PMultiIdentificador> copy = new ArrayList<PMultiIdentificador>(node.getMultiIdentificador());
            for(PMultiIdentificador e : copy)
            {
                e.apply(this);
            }
        }
        outAMultiploId(node);
    }

    public void inAUnicoComando(AUnicoComando node)
    {
        defaultIn(node);
    }

    public void outAUnicoComando(AUnicoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoComando(AUnicoComando node)
    {
        inAUnicoComando(node);
        if(node.getDefinicaoComando() != null)
        {
            node.getDefinicaoComando().apply(this);
        }
        outAUnicoComando(node);
    }

    public void inAMultiploComando(AMultiploComando node)
    {
        defaultIn(node);
    }

    public void outAMultiploComando(AMultiploComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploComando(AMultiploComando node)
    {
        inAMultiploComando(node);
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getDefinicaoComando() != null)
        {
            node.getDefinicaoComando().apply(this);
        }
        outAMultiploComando(node);
    }

    public void inADeclAtribuicaoDefinicaoComando(ADeclAtribuicaoDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclAtribuicaoDefinicaoComando(ADeclAtribuicaoDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclAtribuicaoDefinicaoComando(ADeclAtribuicaoDefinicaoComando node)
    {
        inADeclAtribuicaoDefinicaoComando(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outADeclAtribuicaoDefinicaoComando(node);
    }

    public void inAAtribuicaoExpLogicaDefinicaoComando(AAtribuicaoExpLogicaDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outAAtribuicaoExpLogicaDefinicaoComando(AAtribuicaoExpLogicaDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribuicaoExpLogicaDefinicaoComando(AAtribuicaoExpLogicaDefinicaoComando node)
    {
        inAAtribuicaoExpLogicaDefinicaoComando(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAAtribuicaoExpLogicaDefinicaoComando(node);
    }

    public void inADeclLeiaDefinicaoComando(ADeclLeiaDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclLeiaDefinicaoComando(ADeclLeiaDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclLeiaDefinicaoComando(ADeclLeiaDefinicaoComando node)
    {
        inADeclLeiaDefinicaoComando(node);
        if(node.getLeia() != null)
        {
            node.getLeia().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getMultiploId() != null)
        {
            node.getMultiploId().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outADeclLeiaDefinicaoComando(node);
    }

    public void inADeclEscrevaDefinicaoComando(ADeclEscrevaDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclEscrevaDefinicaoComando(ADeclEscrevaDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclEscrevaDefinicaoComando(ADeclEscrevaDefinicaoComando node)
    {
        inADeclEscrevaDefinicaoComando(node);
        if(node.getEscreva() != null)
        {
            node.getEscreva().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getMultiplaExp() != null)
        {
            node.getMultiplaExp().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outADeclEscrevaDefinicaoComando(node);
    }

    public void inAEscrevaExpLogicaDefinicaoComando(AEscrevaExpLogicaDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outAEscrevaExpLogicaDefinicaoComando(AEscrevaExpLogicaDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEscrevaExpLogicaDefinicaoComando(AEscrevaExpLogicaDefinicaoComando node)
    {
        inAEscrevaExpLogicaDefinicaoComando(node);
        if(node.getEscreva() != null)
        {
            node.getEscreva().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getMultiplaExp() != null)
        {
            node.getMultiplaExp().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAEscrevaExpLogicaDefinicaoComando(node);
    }

    public void inADeclAvalieDefinicaoComando(ADeclAvalieDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclAvalieDefinicaoComando(ADeclAvalieDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclAvalieDefinicaoComando(ADeclAvalieDefinicaoComando node)
    {
        inADeclAvalieDefinicaoComando(node);
        if(node.getAvalie() != null)
        {
            node.getAvalie().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getMultiploCaso() != null)
        {
            node.getMultiploCaso().apply(this);
        }
        if(node.getOpcionalSenaoCaso() != null)
        {
            node.getOpcionalSenaoCaso().apply(this);
        }
        if(node.getFimAvalie() != null)
        {
            node.getFimAvalie().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outADeclAvalieDefinicaoComando(node);
    }

    public void inAAvalieExpLogicaDefinicaoComando(AAvalieExpLogicaDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outAAvalieExpLogicaDefinicaoComando(AAvalieExpLogicaDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAvalieExpLogicaDefinicaoComando(AAvalieExpLogicaDefinicaoComando node)
    {
        inAAvalieExpLogicaDefinicaoComando(node);
        if(node.getAvalie() != null)
        {
            node.getAvalie().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getMultiploCaso() != null)
        {
            node.getMultiploCaso().apply(this);
        }
        if(node.getOpcionalSenaoCaso() != null)
        {
            node.getOpcionalSenaoCaso().apply(this);
        }
        if(node.getFimAvalie() != null)
        {
            node.getFimAvalie().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outAAvalieExpLogicaDefinicaoComando(node);
    }

    public void inADeclEnquantoDefinicaoComando(ADeclEnquantoDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclEnquantoDefinicaoComando(ADeclEnquantoDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclEnquantoDefinicaoComando(ADeclEnquantoDefinicaoComando node)
    {
        inADeclEnquantoDefinicaoComando(node);
        if(node.getEnquanto() != null)
        {
            node.getEnquanto().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getFaca() != null)
        {
            node.getFaca().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getFimEnquanto() != null)
        {
            node.getFimEnquanto().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outADeclEnquantoDefinicaoComando(node);
    }

    public void inADeclRepitaDefinicaoComando(ADeclRepitaDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclRepitaDefinicaoComando(ADeclRepitaDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclRepitaDefinicaoComando(ADeclRepitaDefinicaoComando node)
    {
        inADeclRepitaDefinicaoComando(node);
        if(node.getRepita() != null)
        {
            node.getRepita().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getAte() != null)
        {
            node.getAte().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outADeclRepitaDefinicaoComando(node);
    }

    public void inADeclParaAteDefinicaoComando(ADeclParaAteDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclParaAteDefinicaoComando(ADeclParaAteDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclParaAteDefinicaoComando(ADeclParaAteDefinicaoComando node)
    {
        inADeclParaAteDefinicaoComando(node);
        if(node.getPara() != null)
        {
            node.getPara().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getDe() != null)
        {
            node.getDe().apply(this);
        }
        if(node.getNumInteiro() != null)
        {
            node.getNumInteiro().apply(this);
        }
        if(node.getAte() != null)
        {
            node.getAte().apply(this);
        }
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        if(node.getFaca() != null)
        {
            node.getFaca().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getFimPara() != null)
        {
            node.getFimPara().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outADeclParaAteDefinicaoComando(node);
    }

    public void inADeclParaPassoDefinicaoComando(ADeclParaPassoDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclParaPassoDefinicaoComando(ADeclParaPassoDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclParaPassoDefinicaoComando(ADeclParaPassoDefinicaoComando node)
    {
        inADeclParaPassoDefinicaoComando(node);
        if(node.getPara() != null)
        {
            node.getPara().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getDe() != null)
        {
            node.getDe().apply(this);
        }
        if(node.getNumInteiro() != null)
        {
            node.getNumInteiro().apply(this);
        }
        if(node.getPasso() != null)
        {
            node.getPasso().apply(this);
        }
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        if(node.getAte() != null)
        {
            node.getAte().apply(this);
        }
        if(node.getNInt() != null)
        {
            node.getNInt().apply(this);
        }
        if(node.getFaca() != null)
        {
            node.getFaca().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getFimPara() != null)
        {
            node.getFimPara().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outADeclParaPassoDefinicaoComando(node);
    }

    public void inADeclSeDefinicaoComando(ADeclSeDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclSeDefinicaoComando(ADeclSeDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclSeDefinicaoComando(ADeclSeDefinicaoComando node)
    {
        inADeclSeDefinicaoComando(node);
        if(node.getSe() != null)
        {
            node.getSe().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getEntao() != null)
        {
            node.getEntao().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getOpcionalSenaoSe() != null)
        {
            node.getOpcionalSenaoSe().apply(this);
        }
        if(node.getFimSe() != null)
        {
            node.getFimSe().apply(this);
        }
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        outADeclSeDefinicaoComando(node);
    }

    public void inAOpcionalSenaoSe(AOpcionalSenaoSe node)
    {
        defaultIn(node);
    }

    public void outAOpcionalSenaoSe(AOpcionalSenaoSe node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOpcionalSenaoSe(AOpcionalSenaoSe node)
    {
        inAOpcionalSenaoSe(node);
        if(node.getSenaoSe() != null)
        {
            node.getSenaoSe().apply(this);
        }
        outAOpcionalSenaoSe(node);
    }

    public void inASenaoSe(ASenaoSe node)
    {
        defaultIn(node);
    }

    public void outASenaoSe(ASenaoSe node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASenaoSe(ASenaoSe node)
    {
        inASenaoSe(node);
        if(node.getSenao() != null)
        {
            node.getSenao().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outASenaoSe(node);
    }

    public void inAOpcionalSenaoCaso(AOpcionalSenaoCaso node)
    {
        defaultIn(node);
    }

    public void outAOpcionalSenaoCaso(AOpcionalSenaoCaso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOpcionalSenaoCaso(AOpcionalSenaoCaso node)
    {
        inAOpcionalSenaoCaso(node);
        if(node.getSenaoCaso() != null)
        {
            node.getSenaoCaso().apply(this);
        }
        outAOpcionalSenaoCaso(node);
    }

    public void inASenaoCaso(ASenaoCaso node)
    {
        defaultIn(node);
    }

    public void outASenaoCaso(ASenaoCaso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASenaoCaso(ASenaoCaso node)
    {
        inASenaoCaso(node);
        if(node.getSenao() != null)
        {
            node.getSenao().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outASenaoCaso(node);
    }

    public void inAMultiploCaso(AMultiploCaso node)
    {
        defaultIn(node);
    }

    public void outAMultiploCaso(AMultiploCaso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploCaso(AMultiploCaso node)
    {
        inAMultiploCaso(node);
        {
            List<PDefinicaoCaso> copy = new ArrayList<PDefinicaoCaso>(node.getDefinicaoCaso());
            for(PDefinicaoCaso e : copy)
            {
                e.apply(this);
            }
        }
        outAMultiploCaso(node);
    }

    public void inADefinicaoCaso(ADefinicaoCaso node)
    {
        defaultIn(node);
    }

    public void outADefinicaoCaso(ADefinicaoCaso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefinicaoCaso(ADefinicaoCaso node)
    {
        inADefinicaoCaso(node);
        if(node.getCaso() != null)
        {
            node.getCaso().apply(this);
        }
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outADefinicaoCaso(node);
    }

    public void inAExpAritMultiExp(AExpAritMultiExp node)
    {
        defaultIn(node);
    }

    public void outAExpAritMultiExp(AExpAritMultiExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpAritMultiExp(AExpAritMultiExp node)
    {
        inAExpAritMultiExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        outAExpAritMultiExp(node);
    }

    public void inAExpressaoLogicaMultiExp(AExpressaoLogicaMultiExp node)
    {
        defaultIn(node);
    }

    public void outAExpressaoLogicaMultiExp(AExpressaoLogicaMultiExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpressaoLogicaMultiExp(AExpressaoLogicaMultiExp node)
    {
        inAExpressaoLogicaMultiExp(node);
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        outAExpressaoLogicaMultiExp(node);
    }

    public void inAMultiplaExp(AMultiplaExp node)
    {
        defaultIn(node);
    }

    public void outAMultiplaExp(AMultiplaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplaExp(AMultiplaExp node)
    {
        inAMultiplaExp(node);
        {
            List<PMultiExp> copy = new ArrayList<PMultiExp>(node.getMultiExp());
            for(PMultiExp e : copy)
            {
                e.apply(this);
            }
        }
        outAMultiplaExp(node);
    }

    public void inAMenosUnarioExp(AMenosUnarioExp node)
    {
        defaultIn(node);
    }

    public void outAMenosUnarioExp(AMenosUnarioExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenosUnarioExp(AMenosUnarioExp node)
    {
        inAMenosUnarioExp(node);
        if(node.getMenos() != null)
        {
            node.getMenos().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAMenosUnarioExp(node);
    }

    public void inAExpressaoExp(AExpressaoExp node)
    {
        defaultIn(node);
    }

    public void outAExpressaoExp(AExpressaoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpressaoExp(AExpressaoExp node)
    {
        inAExpressaoExp(node);
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        outAExpressaoExp(node);
    }

    public void inATermoExpressao(ATermoExpressao node)
    {
        defaultIn(node);
    }

    public void outATermoExpressao(ATermoExpressao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATermoExpressao(ATermoExpressao node)
    {
        inATermoExpressao(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outATermoExpressao(node);
    }

    public void inAMaisExpressao(AMaisExpressao node)
    {
        defaultIn(node);
    }

    public void outAMaisExpressao(AMaisExpressao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaisExpressao(AMaisExpressao node)
    {
        inAMaisExpressao(node);
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getMais() != null)
        {
            node.getMais().apply(this);
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outAMaisExpressao(node);
    }

    public void inAMenosExpressao(AMenosExpressao node)
    {
        defaultIn(node);
    }

    public void outAMenosExpressao(AMenosExpressao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenosExpressao(AMenosExpressao node)
    {
        inAMenosExpressao(node);
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getMenos() != null)
        {
            node.getMenos().apply(this);
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outAMenosExpressao(node);
    }

    public void inAFatorTermo(AFatorTermo node)
    {
        defaultIn(node);
    }

    public void outAFatorTermo(AFatorTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFatorTermo(AFatorTermo node)
    {
        inAFatorTermo(node);
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outAFatorTermo(node);
    }

    public void inAMultiplicacaoTermo(AMultiplicacaoTermo node)
    {
        defaultIn(node);
    }

    public void outAMultiplicacaoTermo(AMultiplicacaoTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplicacaoTermo(AMultiplicacaoTermo node)
    {
        inAMultiplicacaoTermo(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getMult() != null)
        {
            node.getMult().apply(this);
        }
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outAMultiplicacaoTermo(node);
    }

    public void inADivisaoTermo(ADivisaoTermo node)
    {
        defaultIn(node);
    }

    public void outADivisaoTermo(ADivisaoTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivisaoTermo(ADivisaoTermo node)
    {
        inADivisaoTermo(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outADivisaoTermo(node);
    }

    public void inAIdentificadorFator(AIdentificadorFator node)
    {
        defaultIn(node);
    }

    public void outAIdentificadorFator(AIdentificadorFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdentificadorFator(AIdentificadorFator node)
    {
        inAIdentificadorFator(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdentificadorFator(node);
    }

    public void inAValorFator(AValorFator node)
    {
        defaultIn(node);
    }

    public void outAValorFator(AValorFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAValorFator(AValorFator node)
    {
        inAValorFator(node);
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        outAValorFator(node);
    }

    public void inAExpFator(AExpFator node)
    {
        defaultIn(node);
    }

    public void outAExpFator(AExpFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpFator(AExpFator node)
    {
        inAExpFator(node);
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        outAExpFator(node);
    }

    public void inANegacaoExpLogica(ANegacaoExpLogica node)
    {
        defaultIn(node);
    }

    public void outANegacaoExpLogica(ANegacaoExpLogica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegacaoExpLogica(ANegacaoExpLogica node)
    {
        inANegacaoExpLogica(node);
        if(node.getNao() != null)
        {
            node.getNao().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        outANegacaoExpLogica(node);
    }

    public void inALogicaExpLogica(ALogicaExpLogica node)
    {
        defaultIn(node);
    }

    public void outALogicaExpLogica(ALogicaExpLogica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALogicaExpLogica(ALogicaExpLogica node)
    {
        inALogicaExpLogica(node);
        if(node.getLogica() != null)
        {
            node.getLogica().apply(this);
        }
        outALogicaExpLogica(node);
    }

    public void inAExpOuLogica(AExpOuLogica node)
    {
        defaultIn(node);
    }

    public void outAExpOuLogica(AExpOuLogica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpOuLogica(AExpOuLogica node)
    {
        inAExpOuLogica(node);
        if(node.getLogica() != null)
        {
            node.getLogica().apply(this);
        }
        if(node.getOu() != null)
        {
            node.getOu().apply(this);
        }
        if(node.getItem() != null)
        {
            node.getItem().apply(this);
        }
        outAExpOuLogica(node);
    }

    public void inAItemOuLogica(AItemOuLogica node)
    {
        defaultIn(node);
    }

    public void outAItemOuLogica(AItemOuLogica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAItemOuLogica(AItemOuLogica node)
    {
        inAItemOuLogica(node);
        if(node.getItem() != null)
        {
            node.getItem().apply(this);
        }
        outAItemOuLogica(node);
    }

    public void inAExpXouItem(AExpXouItem node)
    {
        defaultIn(node);
    }

    public void outAExpXouItem(AExpXouItem node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpXouItem(AExpXouItem node)
    {
        inAExpXouItem(node);
        if(node.getItem() != null)
        {
            node.getItem().apply(this);
        }
        if(node.getXou() != null)
        {
            node.getXou().apply(this);
        }
        if(node.getLogTermo() != null)
        {
            node.getLogTermo().apply(this);
        }
        outAExpXouItem(node);
    }

    public void inAItemXouItem(AItemXouItem node)
    {
        defaultIn(node);
    }

    public void outAItemXouItem(AItemXouItem node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAItemXouItem(AItemXouItem node)
    {
        inAItemXouItem(node);
        if(node.getLogTermo() != null)
        {
            node.getLogTermo().apply(this);
        }
        outAItemXouItem(node);
    }

    public void inAExpELogTermo(AExpELogTermo node)
    {
        defaultIn(node);
    }

    public void outAExpELogTermo(AExpELogTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpELogTermo(AExpELogTermo node)
    {
        inAExpELogTermo(node);
        if(node.getLogTermo() != null)
        {
            node.getLogTermo().apply(this);
        }
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        if(node.getRelacional() != null)
        {
            node.getRelacional().apply(this);
        }
        outAExpELogTermo(node);
    }

    public void inARelacioLogTermo(ARelacioLogTermo node)
    {
        defaultIn(node);
    }

    public void outARelacioLogTermo(ARelacioLogTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacioLogTermo(ARelacioLogTermo node)
    {
        inARelacioLogTermo(node);
        if(node.getRelacional() != null)
        {
            node.getRelacional().apply(this);
        }
        outARelacioLogTermo(node);
    }

    public void inAExpParLogTermo(AExpParLogTermo node)
    {
        defaultIn(node);
    }

    public void outAExpParLogTermo(AExpParLogTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpParLogTermo(AExpParLogTermo node)
    {
        inAExpParLogTermo(node);
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        outAExpParLogTermo(node);
    }

    public void inARelacionalRelacional(ARelacionalRelacional node)
    {
        defaultIn(node);
    }

    public void outARelacionalRelacional(ARelacionalRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacionalRelacional(ARelacionalRelacional node)
    {
        inARelacionalRelacional(node);
        if(node.getL() != null)
        {
            node.getL().apply(this);
        }
        if(node.getOperadores() != null)
        {
            node.getOperadores().apply(this);
        }
        if(node.getR() != null)
        {
            node.getR().apply(this);
        }
        outARelacionalRelacional(node);
    }

    public void inAIgualOperadores(AIgualOperadores node)
    {
        defaultIn(node);
    }

    public void outAIgualOperadores(AIgualOperadores node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualOperadores(AIgualOperadores node)
    {
        inAIgualOperadores(node);
        if(node.getIgualLog() != null)
        {
            node.getIgualLog().apply(this);
        }
        outAIgualOperadores(node);
    }

    public void inADiferenteOperadores(ADiferenteOperadores node)
    {
        defaultIn(node);
    }

    public void outADiferenteOperadores(ADiferenteOperadores node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADiferenteOperadores(ADiferenteOperadores node)
    {
        inADiferenteOperadores(node);
        if(node.getDiferente() != null)
        {
            node.getDiferente().apply(this);
        }
        outADiferenteOperadores(node);
    }

    public void inAOperadores(AOperadores node)
    {
        defaultIn(node);
    }

    public void outAOperadores(AOperadores node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOperadores(AOperadores node)
    {
        inAOperadores(node);
        if(node.getOper() != null)
        {
            node.getOper().apply(this);
        }
        outAOperadores(node);
    }

    public void inAMenorOper(AMenorOper node)
    {
        defaultIn(node);
    }

    public void outAMenorOper(AMenorOper node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorOper(AMenorOper node)
    {
        inAMenorOper(node);
        if(node.getMenor() != null)
        {
            node.getMenor().apply(this);
        }
        outAMenorOper(node);
    }

    public void inAMaiorOper(AMaiorOper node)
    {
        defaultIn(node);
    }

    public void outAMaiorOper(AMaiorOper node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorOper(AMaiorOper node)
    {
        inAMaiorOper(node);
        if(node.getMaior() != null)
        {
            node.getMaior().apply(this);
        }
        outAMaiorOper(node);
    }

    public void inAMenorIgualOper(AMenorIgualOper node)
    {
        defaultIn(node);
    }

    public void outAMenorIgualOper(AMenorIgualOper node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorIgualOper(AMenorIgualOper node)
    {
        inAMenorIgualOper(node);
        if(node.getMenorIgual() != null)
        {
            node.getMenorIgual().apply(this);
        }
        outAMenorIgualOper(node);
    }

    public void inAMaiorIgualOper(AMaiorIgualOper node)
    {
        defaultIn(node);
    }

    public void outAMaiorIgualOper(AMaiorIgualOper node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorIgualOper(AMaiorIgualOper node)
    {
        inAMaiorIgualOper(node);
        if(node.getMaiorIgual() != null)
        {
            node.getMaiorIgual().apply(this);
        }
        outAMaiorIgualOper(node);
    }
}
