/* This file was generated by SableCC (http://www.sablecc.org/). */

package analysis;

import java.util.*;
import node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPProgram().apply(this);
        outStart(node);
    }

    public void inAProgram(AProgram node)
    {
        defaultIn(node);
    }

    public void outAProgram(AProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProgram(AProgram node)
    {
        inAProgram(node);
        if(node.getFim() != null)
        {
            node.getFim().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getDeclaracao() != null)
        {
            node.getDeclaracao().apply(this);
        }
        if(node.getInicio() != null)
        {
            node.getInicio().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPrograma() != null)
        {
            node.getPrograma().apply(this);
        }
        outAProgram(node);
    }

    public void inAUnicoDeclaracao(AUnicoDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAUnicoDeclaracao(AUnicoDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoDeclaracao(AUnicoDeclaracao node)
    {
        inAUnicoDeclaracao(node);
        if(node.getVariavelDefinicao() != null)
        {
            node.getVariavelDefinicao().apply(this);
        }
        outAUnicoDeclaracao(node);
    }

    public void inAMultiploDeclaracao(AMultiploDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAMultiploDeclaracao(AMultiploDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploDeclaracao(AMultiploDeclaracao node)
    {
        inAMultiploDeclaracao(node);
        if(node.getVariavelDefinicao() != null)
        {
            node.getVariavelDefinicao().apply(this);
        }
        if(node.getDeclaracao() != null)
        {
            node.getDeclaracao().apply(this);
        }
        outAMultiploDeclaracao(node);
    }

    public void inAConstDeclaracao(AConstDeclaracao node)
    {
        defaultIn(node);
    }

    public void outAConstDeclaracao(AConstDeclaracao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConstDeclaracao(AConstDeclaracao node)
    {
        inAConstDeclaracao(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getConstante() != null)
        {
            node.getConstante().apply(this);
        }
        outAConstDeclaracao(node);
    }

    public void inAVariavelDefinicao(AVariavelDefinicao node)
    {
        defaultIn(node);
    }

    public void outAVariavelDefinicao(AVariavelDefinicao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariavelDefinicao(AVariavelDefinicao node)
    {
        inAVariavelDefinicao(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getMultiploId() != null)
        {
            node.getMultiploId().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        outAVariavelDefinicao(node);
    }

    public void inAUnicoIdentificador(AUnicoIdentificador node)
    {
        defaultIn(node);
    }

    public void outAUnicoIdentificador(AUnicoIdentificador node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoIdentificador(AUnicoIdentificador node)
    {
        inAUnicoIdentificador(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAUnicoIdentificador(node);
    }

    public void inAMultiploIdentificador(AMultiploIdentificador node)
    {
        defaultIn(node);
    }

    public void outAMultiploIdentificador(AMultiploIdentificador node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploIdentificador(AMultiploIdentificador node)
    {
        inAMultiploIdentificador(node);
        if(node.getRColc() != null)
        {
            node.getRColc().apply(this);
        }
        if(node.getNumInteiro() != null)
        {
            node.getNumInteiro().apply(this);
        }
        if(node.getLColc() != null)
        {
            node.getLColc().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAMultiploIdentificador(node);
    }

    public void inAStringValor(AStringValor node)
    {
        defaultIn(node);
    }

    public void outAStringValor(AStringValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringValor(AStringValor node)
    {
        inAStringValor(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAStringValor(node);
    }

    public void inAInteiroValor(AInteiroValor node)
    {
        defaultIn(node);
    }

    public void outAInteiroValor(AInteiroValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInteiroValor(AInteiroValor node)
    {
        inAInteiroValor(node);
        if(node.getNumInteiro() != null)
        {
            node.getNumInteiro().apply(this);
        }
        outAInteiroValor(node);
    }

    public void inARealValor(ARealValor node)
    {
        defaultIn(node);
    }

    public void outARealValor(ARealValor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealValor(ARealValor node)
    {
        inARealValor(node);
        if(node.getNumReal() != null)
        {
            node.getNumReal().apply(this);
        }
        outARealValor(node);
    }

    public void inATipoRealTipo(ATipoRealTipo node)
    {
        defaultIn(node);
    }

    public void outATipoRealTipo(ATipoRealTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoRealTipo(ATipoRealTipo node)
    {
        inATipoRealTipo(node);
        if(node.getReal() != null)
        {
            node.getReal().apply(this);
        }
        outATipoRealTipo(node);
    }

    public void inATipoIntTipo(ATipoIntTipo node)
    {
        defaultIn(node);
    }

    public void outATipoIntTipo(ATipoIntTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoIntTipo(ATipoIntTipo node)
    {
        inATipoIntTipo(node);
        if(node.getInteiro() != null)
        {
            node.getInteiro().apply(this);
        }
        outATipoIntTipo(node);
    }

    public void inATipoCaractereTipo(ATipoCaractereTipo node)
    {
        defaultIn(node);
    }

    public void outATipoCaractereTipo(ATipoCaractereTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoCaractereTipo(ATipoCaractereTipo node)
    {
        inATipoCaractereTipo(node);
        if(node.getCaractere() != null)
        {
            node.getCaractere().apply(this);
        }
        outATipoCaractereTipo(node);
    }

    public void inAMultiIdentificador(AMultiIdentificador node)
    {
        defaultIn(node);
    }

    public void outAMultiIdentificador(AMultiIdentificador node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiIdentificador(AMultiIdentificador node)
    {
        inAMultiIdentificador(node);
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outAMultiIdentificador(node);
    }

    public void inAMultiploId(AMultiploId node)
    {
        defaultIn(node);
    }

    public void outAMultiploId(AMultiploId node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploId(AMultiploId node)
    {
        inAMultiploId(node);
        {
            List<PMultiIdentificador> copy = new ArrayList<PMultiIdentificador>(node.getMultiIdentificador());
            Collections.reverse(copy);
            for(PMultiIdentificador e : copy)
            {
                e.apply(this);
            }
        }
        outAMultiploId(node);
    }

    public void inAUnicoComando(AUnicoComando node)
    {
        defaultIn(node);
    }

    public void outAUnicoComando(AUnicoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUnicoComando(AUnicoComando node)
    {
        inAUnicoComando(node);
        if(node.getDefinicaoComando() != null)
        {
            node.getDefinicaoComando().apply(this);
        }
        outAUnicoComando(node);
    }

    public void inAMultiploComando(AMultiploComando node)
    {
        defaultIn(node);
    }

    public void outAMultiploComando(AMultiploComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploComando(AMultiploComando node)
    {
        inAMultiploComando(node);
        if(node.getDefinicaoComando() != null)
        {
            node.getDefinicaoComando().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outAMultiploComando(node);
    }

    public void inADeclAtribuicaoDefinicaoComando(ADeclAtribuicaoDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclAtribuicaoDefinicaoComando(ADeclAtribuicaoDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclAtribuicaoDefinicaoComando(ADeclAtribuicaoDefinicaoComando node)
    {
        inADeclAtribuicaoDefinicaoComando(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outADeclAtribuicaoDefinicaoComando(node);
    }

    public void inADeclLeiaDefinicaoComando(ADeclLeiaDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclLeiaDefinicaoComando(ADeclLeiaDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclLeiaDefinicaoComando(ADeclLeiaDefinicaoComando node)
    {
        inADeclLeiaDefinicaoComando(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getMultiploId() != null)
        {
            node.getMultiploId().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getLeia() != null)
        {
            node.getLeia().apply(this);
        }
        outADeclLeiaDefinicaoComando(node);
    }

    public void inADeclEscrevaDefinicaoComando(ADeclEscrevaDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclEscrevaDefinicaoComando(ADeclEscrevaDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclEscrevaDefinicaoComando(ADeclEscrevaDefinicaoComando node)
    {
        inADeclEscrevaDefinicaoComando(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getMultiplaExp() != null)
        {
            node.getMultiplaExp().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getEscreva() != null)
        {
            node.getEscreva().apply(this);
        }
        outADeclEscrevaDefinicaoComando(node);
    }

    public void inADeclAvalieDefinicaoComando(ADeclAvalieDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclAvalieDefinicaoComando(ADeclAvalieDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclAvalieDefinicaoComando(ADeclAvalieDefinicaoComando node)
    {
        inADeclAvalieDefinicaoComando(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getFimAvalie() != null)
        {
            node.getFimAvalie().apply(this);
        }
        if(node.getOpcionalSenaoCaso() != null)
        {
            node.getOpcionalSenaoCaso().apply(this);
        }
        if(node.getMultiploCaso() != null)
        {
            node.getMultiploCaso().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getAvalie() != null)
        {
            node.getAvalie().apply(this);
        }
        outADeclAvalieDefinicaoComando(node);
    }

    public void inADeclEnquantoCmdDefinicaoComando(ADeclEnquantoCmdDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclEnquantoCmdDefinicaoComando(ADeclEnquantoCmdDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclEnquantoCmdDefinicaoComando(ADeclEnquantoCmdDefinicaoComando node)
    {
        inADeclEnquantoCmdDefinicaoComando(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getFimEnquanto() != null)
        {
            node.getFimEnquanto().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getFaca() != null)
        {
            node.getFaca().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getEnquanto() != null)
        {
            node.getEnquanto().apply(this);
        }
        outADeclEnquantoCmdDefinicaoComando(node);
    }

    public void inADeclEnquantoDefinicaoComando(ADeclEnquantoDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclEnquantoDefinicaoComando(ADeclEnquantoDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclEnquantoDefinicaoComando(ADeclEnquantoDefinicaoComando node)
    {
        inADeclEnquantoDefinicaoComando(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getFimEnquanto() != null)
        {
            node.getFimEnquanto().apply(this);
        }
        if(node.getFaca() != null)
        {
            node.getFaca().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getEnquanto() != null)
        {
            node.getEnquanto().apply(this);
        }
        outADeclEnquantoDefinicaoComando(node);
    }

    public void inADeclRepitaCmdDefinicaoComando(ADeclRepitaCmdDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclRepitaCmdDefinicaoComando(ADeclRepitaCmdDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclRepitaCmdDefinicaoComando(ADeclRepitaCmdDefinicaoComando node)
    {
        inADeclRepitaCmdDefinicaoComando(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getAte() != null)
        {
            node.getAte().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getRepita() != null)
        {
            node.getRepita().apply(this);
        }
        outADeclRepitaCmdDefinicaoComando(node);
    }

    public void inADeclRepitaDefinicaoComando(ADeclRepitaDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclRepitaDefinicaoComando(ADeclRepitaDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclRepitaDefinicaoComando(ADeclRepitaDefinicaoComando node)
    {
        inADeclRepitaDefinicaoComando(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getAte() != null)
        {
            node.getAte().apply(this);
        }
        if(node.getRepita() != null)
        {
            node.getRepita().apply(this);
        }
        outADeclRepitaDefinicaoComando(node);
    }

    public void inADeclParaAteCmdDefinicaoComando(ADeclParaAteCmdDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclParaAteCmdDefinicaoComando(ADeclParaAteCmdDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclParaAteCmdDefinicaoComando(ADeclParaAteCmdDefinicaoComando node)
    {
        inADeclParaAteCmdDefinicaoComando(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getFimPara() != null)
        {
            node.getFimPara().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getFaca() != null)
        {
            node.getFaca().apply(this);
        }
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        if(node.getAte() != null)
        {
            node.getAte().apply(this);
        }
        if(node.getNumInteiro() != null)
        {
            node.getNumInteiro().apply(this);
        }
        if(node.getDe() != null)
        {
            node.getDe().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getPara() != null)
        {
            node.getPara().apply(this);
        }
        outADeclParaAteCmdDefinicaoComando(node);
    }

    public void inADeclParaAteDefinicaoComando(ADeclParaAteDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclParaAteDefinicaoComando(ADeclParaAteDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclParaAteDefinicaoComando(ADeclParaAteDefinicaoComando node)
    {
        inADeclParaAteDefinicaoComando(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getFimPara() != null)
        {
            node.getFimPara().apply(this);
        }
        if(node.getFaca() != null)
        {
            node.getFaca().apply(this);
        }
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        if(node.getAte() != null)
        {
            node.getAte().apply(this);
        }
        if(node.getNumInteiro() != null)
        {
            node.getNumInteiro().apply(this);
        }
        if(node.getDe() != null)
        {
            node.getDe().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getPara() != null)
        {
            node.getPara().apply(this);
        }
        outADeclParaAteDefinicaoComando(node);
    }

    public void inADeclParaPassoCmdDefinicaoComando(ADeclParaPassoCmdDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclParaPassoCmdDefinicaoComando(ADeclParaPassoCmdDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclParaPassoCmdDefinicaoComando(ADeclParaPassoCmdDefinicaoComando node)
    {
        inADeclParaPassoCmdDefinicaoComando(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getFimPara() != null)
        {
            node.getFimPara().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getFaca() != null)
        {
            node.getFaca().apply(this);
        }
        if(node.getNInt() != null)
        {
            node.getNInt().apply(this);
        }
        if(node.getAte() != null)
        {
            node.getAte().apply(this);
        }
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        if(node.getPasso() != null)
        {
            node.getPasso().apply(this);
        }
        if(node.getNumInteiro() != null)
        {
            node.getNumInteiro().apply(this);
        }
        if(node.getDe() != null)
        {
            node.getDe().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getPara() != null)
        {
            node.getPara().apply(this);
        }
        outADeclParaPassoCmdDefinicaoComando(node);
    }

    public void inADeclParaPassoDefinicaoComando(ADeclParaPassoDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclParaPassoDefinicaoComando(ADeclParaPassoDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclParaPassoDefinicaoComando(ADeclParaPassoDefinicaoComando node)
    {
        inADeclParaPassoDefinicaoComando(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getFimPara() != null)
        {
            node.getFimPara().apply(this);
        }
        if(node.getFaca() != null)
        {
            node.getFaca().apply(this);
        }
        if(node.getNInt() != null)
        {
            node.getNInt().apply(this);
        }
        if(node.getAte() != null)
        {
            node.getAte().apply(this);
        }
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        if(node.getPasso() != null)
        {
            node.getPasso().apply(this);
        }
        if(node.getNumInteiro() != null)
        {
            node.getNumInteiro().apply(this);
        }
        if(node.getDe() != null)
        {
            node.getDe().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getPara() != null)
        {
            node.getPara().apply(this);
        }
        outADeclParaPassoDefinicaoComando(node);
    }

    public void inADeclSeCmdDefinicaoComando(ADeclSeCmdDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclSeCmdDefinicaoComando(ADeclSeCmdDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclSeCmdDefinicaoComando(ADeclSeCmdDefinicaoComando node)
    {
        inADeclSeCmdDefinicaoComando(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getFimSe() != null)
        {
            node.getFimSe().apply(this);
        }
        if(node.getOpcionalSenaoSe() != null)
        {
            node.getOpcionalSenaoSe().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getEntao() != null)
        {
            node.getEntao().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getSe() != null)
        {
            node.getSe().apply(this);
        }
        outADeclSeCmdDefinicaoComando(node);
    }

    public void inADeclSeDefinicaoComando(ADeclSeDefinicaoComando node)
    {
        defaultIn(node);
    }

    public void outADeclSeDefinicaoComando(ADeclSeDefinicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclSeDefinicaoComando(ADeclSeDefinicaoComando node)
    {
        inADeclSeDefinicaoComando(node);
        if(node.getPontoVirgula() != null)
        {
            node.getPontoVirgula().apply(this);
        }
        if(node.getFimSe() != null)
        {
            node.getFimSe().apply(this);
        }
        if(node.getOpcionalSenaoSe() != null)
        {
            node.getOpcionalSenaoSe().apply(this);
        }
        if(node.getEntao() != null)
        {
            node.getEntao().apply(this);
        }
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getSe() != null)
        {
            node.getSe().apply(this);
        }
        outADeclSeDefinicaoComando(node);
    }

    public void inAOpcionalSenaoSe(AOpcionalSenaoSe node)
    {
        defaultIn(node);
    }

    public void outAOpcionalSenaoSe(AOpcionalSenaoSe node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOpcionalSenaoSe(AOpcionalSenaoSe node)
    {
        inAOpcionalSenaoSe(node);
        if(node.getSenaoSe() != null)
        {
            node.getSenaoSe().apply(this);
        }
        outAOpcionalSenaoSe(node);
    }

    public void inASenaoCmdSenaoSe(ASenaoCmdSenaoSe node)
    {
        defaultIn(node);
    }

    public void outASenaoCmdSenaoSe(ASenaoCmdSenaoSe node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASenaoCmdSenaoSe(ASenaoCmdSenaoSe node)
    {
        inASenaoCmdSenaoSe(node);
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getSenao() != null)
        {
            node.getSenao().apply(this);
        }
        outASenaoCmdSenaoSe(node);
    }

    public void inASenaoSenaoSe(ASenaoSenaoSe node)
    {
        defaultIn(node);
    }

    public void outASenaoSenaoSe(ASenaoSenaoSe node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASenaoSenaoSe(ASenaoSenaoSe node)
    {
        inASenaoSenaoSe(node);
        if(node.getSenao() != null)
        {
            node.getSenao().apply(this);
        }
        outASenaoSenaoSe(node);
    }

    public void inAOpcionalSenaoCaso(AOpcionalSenaoCaso node)
    {
        defaultIn(node);
    }

    public void outAOpcionalSenaoCaso(AOpcionalSenaoCaso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOpcionalSenaoCaso(AOpcionalSenaoCaso node)
    {
        inAOpcionalSenaoCaso(node);
        if(node.getSenaoCaso() != null)
        {
            node.getSenaoCaso().apply(this);
        }
        outAOpcionalSenaoCaso(node);
    }

    public void inACasoCmdSenaoCaso(ACasoCmdSenaoCaso node)
    {
        defaultIn(node);
    }

    public void outACasoCmdSenaoCaso(ACasoCmdSenaoCaso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACasoCmdSenaoCaso(ACasoCmdSenaoCaso node)
    {
        inACasoCmdSenaoCaso(node);
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getSenao() != null)
        {
            node.getSenao().apply(this);
        }
        outACasoCmdSenaoCaso(node);
    }

    public void inACasoSenaoCaso(ACasoSenaoCaso node)
    {
        defaultIn(node);
    }

    public void outACasoSenaoCaso(ACasoSenaoCaso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACasoSenaoCaso(ACasoSenaoCaso node)
    {
        inACasoSenaoCaso(node);
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getSenao() != null)
        {
            node.getSenao().apply(this);
        }
        outACasoSenaoCaso(node);
    }

    public void inAMultiploCaso(AMultiploCaso node)
    {
        defaultIn(node);
    }

    public void outAMultiploCaso(AMultiploCaso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiploCaso(AMultiploCaso node)
    {
        inAMultiploCaso(node);
        {
            List<PDefinicaoCaso> copy = new ArrayList<PDefinicaoCaso>(node.getDefinicaoCaso());
            Collections.reverse(copy);
            for(PDefinicaoCaso e : copy)
            {
                e.apply(this);
            }
        }
        outAMultiploCaso(node);
    }

    public void inADefCasoCmdDefinicaoCaso(ADefCasoCmdDefinicaoCaso node)
    {
        defaultIn(node);
    }

    public void outADefCasoCmdDefinicaoCaso(ADefCasoCmdDefinicaoCaso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefCasoCmdDefinicaoCaso(ADefCasoCmdDefinicaoCaso node)
    {
        inADefCasoCmdDefinicaoCaso(node);
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        if(node.getCaso() != null)
        {
            node.getCaso().apply(this);
        }
        outADefCasoCmdDefinicaoCaso(node);
    }

    public void inADefCasoDefinicaoCaso(ADefCasoDefinicaoCaso node)
    {
        defaultIn(node);
    }

    public void outADefCasoDefinicaoCaso(ADefCasoDefinicaoCaso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefCasoDefinicaoCaso(ADefCasoDefinicaoCaso node)
    {
        inADefCasoDefinicaoCaso(node);
        if(node.getDoisPontos() != null)
        {
            node.getDoisPontos().apply(this);
        }
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        if(node.getCaso() != null)
        {
            node.getCaso().apply(this);
        }
        outADefCasoDefinicaoCaso(node);
    }

    public void inAMultiExp(AMultiExp node)
    {
        defaultIn(node);
    }

    public void outAMultiExp(AMultiExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiExp(AMultiExp node)
    {
        inAMultiExp(node);
        if(node.getVirgula() != null)
        {
            node.getVirgula().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAMultiExp(node);
    }

    public void inAMultiplaExp(AMultiplaExp node)
    {
        defaultIn(node);
    }

    public void outAMultiplaExp(AMultiplaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplaExp(AMultiplaExp node)
    {
        inAMultiplaExp(node);
        {
            List<PMultiExp> copy = new ArrayList<PMultiExp>(node.getMultiExp());
            Collections.reverse(copy);
            for(PMultiExp e : copy)
            {
                e.apply(this);
            }
        }
        outAMultiplaExp(node);
    }

    public void inATermoExp(ATermoExp node)
    {
        defaultIn(node);
    }

    public void outATermoExp(ATermoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATermoExp(ATermoExp node)
    {
        inATermoExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outATermoExp(node);
    }

    public void inAMaisExp(AMaisExp node)
    {
        defaultIn(node);
    }

    public void outAMaisExp(AMaisExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaisExp(AMaisExp node)
    {
        inAMaisExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getMais() != null)
        {
            node.getMais().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAMaisExp(node);
    }

    public void inAMenosExp(AMenosExp node)
    {
        defaultIn(node);
    }

    public void outAMenosExp(AMenosExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenosExp(AMenosExp node)
    {
        inAMenosExp(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getMenos() != null)
        {
            node.getMenos().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAMenosExp(node);
    }

    public void inAFatorTermo(AFatorTermo node)
    {
        defaultIn(node);
    }

    public void outAFatorTermo(AFatorTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFatorTermo(AFatorTermo node)
    {
        inAFatorTermo(node);
        if(node.getUnario() != null)
        {
            node.getUnario().apply(this);
        }
        outAFatorTermo(node);
    }

    public void inAMultiplicacaoTermo(AMultiplicacaoTermo node)
    {
        defaultIn(node);
    }

    public void outAMultiplicacaoTermo(AMultiplicacaoTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplicacaoTermo(AMultiplicacaoTermo node)
    {
        inAMultiplicacaoTermo(node);
        if(node.getUnario() != null)
        {
            node.getUnario().apply(this);
        }
        if(node.getMult() != null)
        {
            node.getMult().apply(this);
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outAMultiplicacaoTermo(node);
    }

    public void inADivisaoTermo(ADivisaoTermo node)
    {
        defaultIn(node);
    }

    public void outADivisaoTermo(ADivisaoTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivisaoTermo(ADivisaoTermo node)
    {
        inADivisaoTermo(node);
        if(node.getUnario() != null)
        {
            node.getUnario().apply(this);
        }
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outADivisaoTermo(node);
    }

    public void inAMenosUnarioUnario(AMenosUnarioUnario node)
    {
        defaultIn(node);
    }

    public void outAMenosUnarioUnario(AMenosUnarioUnario node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenosUnarioUnario(AMenosUnarioUnario node)
    {
        inAMenosUnarioUnario(node);
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        if(node.getMenos() != null)
        {
            node.getMenos().apply(this);
        }
        outAMenosUnarioUnario(node);
    }

    public void inAFatorUnario(AFatorUnario node)
    {
        defaultIn(node);
    }

    public void outAFatorUnario(AFatorUnario node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFatorUnario(AFatorUnario node)
    {
        inAFatorUnario(node);
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outAFatorUnario(node);
    }

    public void inAIdentificadorFator(AIdentificadorFator node)
    {
        defaultIn(node);
    }

    public void outAIdentificadorFator(AIdentificadorFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdentificadorFator(AIdentificadorFator node)
    {
        inAIdentificadorFator(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdentificadorFator(node);
    }

    public void inAValorFator(AValorFator node)
    {
        defaultIn(node);
    }

    public void outAValorFator(AValorFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAValorFator(AValorFator node)
    {
        inAValorFator(node);
        if(node.getValor() != null)
        {
            node.getValor().apply(this);
        }
        outAValorFator(node);
    }

    public void inAExpFator(AExpFator node)
    {
        defaultIn(node);
    }

    public void outAExpFator(AExpFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpFator(AExpFator node)
    {
        inAExpFator(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        outAExpFator(node);
    }

    public void inAExpressaoFator(AExpressaoFator node)
    {
        defaultIn(node);
    }

    public void outAExpressaoFator(AExpressaoFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpressaoFator(AExpressaoFator node)
    {
        inAExpressaoFator(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        outAExpressaoFator(node);
    }

    public void inAExpOuExpLogica(AExpOuExpLogica node)
    {
        defaultIn(node);
    }

    public void outAExpOuExpLogica(AExpOuExpLogica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpOuExpLogica(AExpOuExpLogica node)
    {
        inAExpOuExpLogica(node);
        if(node.getItem() != null)
        {
            node.getItem().apply(this);
        }
        if(node.getOu() != null)
        {
            node.getOu().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        outAExpOuExpLogica(node);
    }

    public void inAItemOuExpLogica(AItemOuExpLogica node)
    {
        defaultIn(node);
    }

    public void outAItemOuExpLogica(AItemOuExpLogica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAItemOuExpLogica(AItemOuExpLogica node)
    {
        inAItemOuExpLogica(node);
        if(node.getItem() != null)
        {
            node.getItem().apply(this);
        }
        outAItemOuExpLogica(node);
    }

    public void inAExpXouItem(AExpXouItem node)
    {
        defaultIn(node);
    }

    public void outAExpXouItem(AExpXouItem node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpXouItem(AExpXouItem node)
    {
        inAExpXouItem(node);
        if(node.getLogTermo() != null)
        {
            node.getLogTermo().apply(this);
        }
        if(node.getXou() != null)
        {
            node.getXou().apply(this);
        }
        if(node.getItem() != null)
        {
            node.getItem().apply(this);
        }
        outAExpXouItem(node);
    }

    public void inAItemXouItem(AItemXouItem node)
    {
        defaultIn(node);
    }

    public void outAItemXouItem(AItemXouItem node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAItemXouItem(AItemXouItem node)
    {
        inAItemXouItem(node);
        if(node.getLogTermo() != null)
        {
            node.getLogTermo().apply(this);
        }
        outAItemXouItem(node);
    }

    public void inAExpELogTermo(AExpELogTermo node)
    {
        defaultIn(node);
    }

    public void outAExpELogTermo(AExpELogTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpELogTermo(AExpELogTermo node)
    {
        inAExpELogTermo(node);
        if(node.getLogFator() != null)
        {
            node.getLogFator().apply(this);
        }
        if(node.getE() != null)
        {
            node.getE().apply(this);
        }
        if(node.getLogTermo() != null)
        {
            node.getLogTermo().apply(this);
        }
        outAExpELogTermo(node);
    }

    public void inATemELogTermo(ATemELogTermo node)
    {
        defaultIn(node);
    }

    public void outATemELogTermo(ATemELogTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATemELogTermo(ATemELogTermo node)
    {
        inATemELogTermo(node);
        if(node.getLogFator() != null)
        {
            node.getLogFator().apply(this);
        }
        outATemELogTermo(node);
    }

    public void inARelacionalLogFator(ARelacionalLogFator node)
    {
        defaultIn(node);
    }

    public void outARelacionalLogFator(ARelacionalLogFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacionalLogFator(ARelacionalLogFator node)
    {
        inARelacionalLogFator(node);
        if(node.getRelacional() != null)
        {
            node.getRelacional().apply(this);
        }
        outARelacionalLogFator(node);
    }

    public void inANegacaoLogFator(ANegacaoLogFator node)
    {
        defaultIn(node);
    }

    public void outANegacaoLogFator(ANegacaoLogFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegacaoLogFator(ANegacaoLogFator node)
    {
        inANegacaoLogFator(node);
        if(node.getRPar() != null)
        {
            node.getRPar().apply(this);
        }
        if(node.getExpLogica() != null)
        {
            node.getExpLogica().apply(this);
        }
        if(node.getLPar() != null)
        {
            node.getLPar().apply(this);
        }
        if(node.getNao() != null)
        {
            node.getNao().apply(this);
        }
        outANegacaoLogFator(node);
    }

    public void inAIgualRelacional(AIgualRelacional node)
    {
        defaultIn(node);
    }

    public void outAIgualRelacional(AIgualRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualRelacional(AIgualRelacional node)
    {
        inAIgualRelacional(node);
        if(node.getR() != null)
        {
            node.getR().apply(this);
        }
        if(node.getIgualLog() != null)
        {
            node.getIgualLog().apply(this);
        }
        if(node.getL() != null)
        {
            node.getL().apply(this);
        }
        outAIgualRelacional(node);
    }

    public void inADiferenteRelacional(ADiferenteRelacional node)
    {
        defaultIn(node);
    }

    public void outADiferenteRelacional(ADiferenteRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADiferenteRelacional(ADiferenteRelacional node)
    {
        inADiferenteRelacional(node);
        if(node.getR() != null)
        {
            node.getR().apply(this);
        }
        if(node.getDiferente() != null)
        {
            node.getDiferente().apply(this);
        }
        if(node.getL() != null)
        {
            node.getL().apply(this);
        }
        outADiferenteRelacional(node);
    }

    public void inAMenorRelacional(AMenorRelacional node)
    {
        defaultIn(node);
    }

    public void outAMenorRelacional(AMenorRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorRelacional(AMenorRelacional node)
    {
        inAMenorRelacional(node);
        if(node.getR() != null)
        {
            node.getR().apply(this);
        }
        if(node.getMenor() != null)
        {
            node.getMenor().apply(this);
        }
        if(node.getL() != null)
        {
            node.getL().apply(this);
        }
        outAMenorRelacional(node);
    }

    public void inAMaiorRelacional(AMaiorRelacional node)
    {
        defaultIn(node);
    }

    public void outAMaiorRelacional(AMaiorRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorRelacional(AMaiorRelacional node)
    {
        inAMaiorRelacional(node);
        if(node.getR() != null)
        {
            node.getR().apply(this);
        }
        if(node.getMaior() != null)
        {
            node.getMaior().apply(this);
        }
        if(node.getL() != null)
        {
            node.getL().apply(this);
        }
        outAMaiorRelacional(node);
    }

    public void inAMenorIgualRelacional(AMenorIgualRelacional node)
    {
        defaultIn(node);
    }

    public void outAMenorIgualRelacional(AMenorIgualRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorIgualRelacional(AMenorIgualRelacional node)
    {
        inAMenorIgualRelacional(node);
        if(node.getR() != null)
        {
            node.getR().apply(this);
        }
        if(node.getMenorIgual() != null)
        {
            node.getMenorIgual().apply(this);
        }
        if(node.getL() != null)
        {
            node.getL().apply(this);
        }
        outAMenorIgualRelacional(node);
    }

    public void inAMaiorIgualRelacional(AMaiorIgualRelacional node)
    {
        defaultIn(node);
    }

    public void outAMaiorIgualRelacional(AMaiorIgualRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorIgualRelacional(AMaiorIgualRelacional node)
    {
        inAMaiorIgualRelacional(node);
        if(node.getR() != null)
        {
            node.getR().apply(this);
        }
        if(node.getMaiorIgual() != null)
        {
            node.getMaiorIgual().apply(this);
        }
        if(node.getL() != null)
        {
            node.getL().apply(this);
        }
        outAMaiorIgualRelacional(node);
    }
}
